### ISSUE TITLE
calculate timings seems broken in V AudioCraft Plus - v2.0.0a

### ISSUE THREAD

**Issue by tob-har** [GrandaddyShmax/audiocraft_plus#27]
Issue: Every field "Time" when using several prompts, shows the maximaum Duration set. Even after executing "calculate timings". Renderd audio is then also just the Max. Duration.

**Comment by GrandaddyShmax** [comment]
The timing is affected by repeat of each segment, duration and overlap.
if for example the maximum duration is 30s then yeah it will show up as max duration for each segment
that is because the first segment will always extend to maximum that is being 30s no matter what duration you set
So if I were to set duration to 80s
Overlap to 20s
Prompt Segmentation to 4
and on each segment repeat 1
Then I should get something like this:
prompt 1: 00:00 - 00:30
prompt 2: 00:31 - 00:40
prompt 3: 00:41 - 00:50
prompt 4: 00:51 - 00:80
The last one is longer because it is the last segment and it will fill it until it reaches the duration you set.
Hope I was able to help you understand it better 😅

**Comment by tob-har** [comment]
arg... sure... just missed to try it wth proper lenght and divisions... sorry for wasting time and thanks for explaining
